controller_ip: 10.140.131.55
controller_pem: cw-admin@10.140.131.55:/home/cw-admin/controller.pem
dns: 8.8.8.8
ntp: 10.140.129.141
domain: dish-wireless.net
vcenter_root: 10.140.129.158/Cheyenne%20DC/host